# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2022 Sascha Brawer <sascha@brawer.ch>
#
# GitHub action to build and test a release binary for the indexer.
# Triggered when a git tag has been pushed to the main branch.
# If all tests pass, we build a container image for production
# and push it to the GitHub container registry.

name: Package
on:
  push:
    branches:
    - 'main'
    tags:
    - v**

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Find container metadata
        id: container-metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/brawer/brandy/indexer
      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          layers: false
          tags: ${{ steps.container-metadata.outputs.tags }}
          labels: ${{ steps.container-metadata.outputs.labels }}
          containerfiles: Containerfile
      - name: Push to GitHub Container Registry
        id: push-to-github
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ghcr.io/brawer/brandy/indexer
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
